# Generated by Django 3.2.9 on 2021-11-05 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categorias', '0003_categoria'),
        ('blog_posts', '0003_auto_20211104_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_categorias.categoria', verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
