# Generated by Django 3.2.9 on 2021-11-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0003_auto_20211104_2312'),
        ('blog_categorias', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
